name: Update librarie on NPM
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: 1. Install dependencies
        run: npm i --legacy-peer-deps

      - name: 2. Create build
        run: npm run build

      - name: 3. Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
